### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by rex-remind101** [rollbar/rollbar-rust#3]
This repo has not had what looks like any significant changes in 3 years, is it dead?

**Comment by cyrusradfar** [comment]
@rex-remind101 no, we have some regression testing and reviews in progress which will break that streak.

**Comment by rex-remind101** [comment]
Great, a major issue we have is we can't set the endpoint _and_ token through an env var. Forking and updating seemed risky given the jvm integration so we've decided to possibly fork https://github.com/RoxasShadow/rollbar-rs which has simpler code for the time being. If this change is planned, and could be made by next week, we may stick with this repo however.

**Comment by cyrusradfar** [comment]
@rex-remind101 ok, let me see what that'll take to fix.

**Comment by ijsnow** [comment]
Hey @rex-remind101, I've been reviewing the sdk for rollbar so good timing!

With regards to setting the access token _and_ endpoint. While there aren't any functions for setting fields on the `Configuration` struct, all the fields are public so you can set them whenever you have access to a mutable configuration object. Does expanding [this buried example](https://github.com/rollbar/rollbar-rust/blob/master/core/src/main.rs#L19-L23) to the following work for you?

```rust
fn make_configuration() -> Configuration {
    let mut conf = Configuration::default();
    conf.access_token = std::env::var("MY_ROLLBAR_TOKEN").ok();
    conf.endpoint = std::env::var("MY_ROLLBAR_ENDPOINT").ok();
    conf
}
```

If not, could you provide an example of something you've tried? I haven't looked at all the code yet so I might be missing the part you're working with.

**Comment by rex-remind101** [comment]
I was going off of the [docs](https://github.com/rollbar/rollbar-rust#configuration), but that looks like what we might need. We'll give it a try when someone gets to this task within a week. Thanks!

**Comment by masimons** [comment]
In main.rs there's an example of creating a message item,  but not a trace item. It seems that traces are handled by a connection to the JVM? Does this library support pure rust stack traces?

**Comment by ijsnow** [comment]
This PR adds the ability to set the endpoint with an `ROLLBAR_ENDPOINT` environment variable. 

https://github.com/rollbar/rollbar-rust/pull/5

**Comment by ijsnow** [comment]
@masimons would you like to catch `panic!`s? If you open another issue with a specific use case it will be easier for me to dig in as I'm orienting myself in the repo as well.
